spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 모든 Eureka 서비스, 게이트웨이 라우팅 규칙 추가
          lower-case-service-id: true
      routes:
        - id: blog-widget
          uri: lb://BLOG-WIDGET
          predicates:
            - Path=/api/**
server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
